### ISSUE TITLE
If a class is not found, make a termgenie API call to see if it's in the queue

### ISSUE THREAD

**Issue by cmungall** [geneontology/amigo#174]
If a class is not found, make a TermGenie API call to see if it's in the queue.

Low priority but nice to have. 2.4?

Also the text on the 404 page could be friendlier.

**Comment by kltm** [comment]
I'm assuming that this is apropos the Paola issue?

Given a TermGenie API and all the JS taffy, would likely not be too hard.

That said, I'm not sure of the use case outside of a very editor-oriented outlook--somebody working on ontology data that's possibly fresher than the GO site's (discounting very important production issues, which is what I think is going on with Paola's term). Otherwise, a normal user would have to edit the URL to get to a term not yet present.

Would it not make more sense to just have links to: a TermGenie page for in-progress terms (a more editor-oriented interface), the page of the current data load, maybe a new search box, etc.?

I would suspect getting to 2.4 will take a while given that a lot of the 2.2 stuff was pushed to 2.3.

**Comment by kltm** [comment]
Old.
