### ISSUE TITLE
Improve speices (taxon) filtering in interactive search by using a taxon subset and a new field

### ISSUE THREAD

**Issue by mellybelly** [geneontology/amigo#209]
It would be awesome if you could facet on species to which there are direct annotations (e.g. minus IEA) 
So for example, I want to know how many/which species have direct annotations to an given GO term, I don't want to see all the upper level taxa.

**Comment by kltm** [comment]
I'm not sure how this wouldn't be covered by the current annotation search, here with evidence, taxon, and direct annotation filtering:

http://amigo2.berkeleybop.org/amigo/search/annotation?q=*:*&fq=evidence_type_closure:%22experimental%20evidence%22&fq=taxon_closure_label:%22Platyrrhini%22&fq=annotation_class_label:%22identical%20protein%20binding%22&sfq=document_category:%22annotation%22

**Comment by mellybelly** [comment]
Well, I think that result isn't quite what I want, because I don't want only the closure of a taxon, I want a list of species with experimentally determined annotations. If there are very many species and annotations, you would have to review every page to determine which species were represented, right?

Also it is not very intuitive for choosing the filters that you have chosen? 
How do I get to to the experimental evidence closure filter?
I find the filters on the left to be slightly unintuitive in their labels, maybe could be displayed hierarchically?

**Comment by cmungall** [comment]
Spoke to @mellybelly, the query "Distribution by species of annotations to sensory perception of smell" available on Gannet and here: http://wiki.geneontology.org/index.php/Example_Solr_Queries#Distribution_by_species_of_annotations_to_sensory_perception_of_smell works for now.

This brings up some issues people are having with amigo taxon facets. I like being able to drill down the taxonomy but this is a geeky obscure use case. Most people just want to find "Human" and filter on that. Sometimes common groupings like mammal are also useful.

As an interim measure, I changed the yaml so that only direct taxa can be filtered within amigo (should be visible on labs instance soon).

But the plan for 2.3 is to have the display show a new facet, taxon_closure_subset, that will be just leaves plus a very limited set of grouping taxa (controlled via a manually edited subset). I suggest:

 * Mammalia
 * Vertebrata
 * Fungi
 * Metazoa
 * Viridiplantae
 * Eukaryota
 * Archaea
 * Bacteria

Yes that's lopsided but so is the annotation distribution. Note that the handy - buttons make composing "Invertebrata" trivial.

This also brings up an interesting experiment we could try, where we populate species as annotated objects, allowing you to query for all species that have sensory perception of smell, and get these back as rows, not facets. However, this doesn't satisfy any GO use case so we will put that on the backburner for now.

**Comment by kltm** [comment]
While we have several things close (including berkeleybop/bbop-js issues), there is nothing is nothing quite like the explanation and proposed fix here for the AmiGO-specific stuff. I'm going to hijack this issue.

**Comment by kltm** [comment]
There is an upstream component that @hdietze will have to help us out with as well.

**Comment by hdietze** [comment]
The code is prepared to generate the new taxon_subset field. Next steps:
 * Create the subset (i.e. owl file with subset annotations)
 * Add owl file to loaded ontology
 * Make sure that the subset is properly configured

**Comment by kltm** [comment]
@hdietze will this mean that we need an additional file for loading here, or is this an include in something that we're already getting?

**Comment by cmungall** [comment]
Additional file for now (it may be integrated into taxslim in future). Let's put it in the usual place go/extensions. Note we don't want to explicitly put the leaves in, these should be assumed.

**Comment by kltm** [comment]
Now code complete in amigo, golr, and owltools. See #247 for the (possibly) site dependent data side of things.
