### ISSUE TITLE
Exclude Reactome GAF from load

### ISSUE THREAD

**Issue by cmungall** [geneontology/amigo#211]
See http://jira.geneontology.org/browse/GO-861

**Comment by kltm** [comment]
While that Makefile is the default representative, to see what happens, you'll have to make changes to:

conf/examples/Makefile.golr.nakama
conf/examples/Makefile.golr.tomodachi

**Comment by kltm** [comment]
I don't think production ever added their Makefiles, so they will have to be tagged on separately to get the changes out.

**Comment by cmungall** [comment]
@kkarra can you add your Makefile

**Comment by kltm** [comment]
@kkarra So we can centrally coordinate necessary data changes, would you be able to commit your Makefile to conf/examples? Ideally we like to be able to make changes to the data being loaded upstream and just have you pull those in as fixes.

**Comment by stuartmiyasato** [comment]
I'm a bit confused.  I've intentionally tried not to modify the GOlr Makefile (and in fact I don't think I have) because the install docs say to make all changes to environment variables rather than editing the Makefile directly.  Is this a change to that methodology?  All the environment variables changes are set in our loading script.

**Comment by cmungall** [comment]
@kltm to advise...

**Comment by kltm** [comment]
I think that's fine, just another way of doing things. However, mind-reading Chris, I think that the end goal is to have all configurations, including production (less and secrets) in version control so that changes and be reviewed and pushed, and debugging can take place more easily.

If you're doing things via a wrapper file, would it be possible to commit those into conf/examples?

Oh, and for the issue at hand, we just need reactome out of there for the next load. :smile:

**Comment by stuartmiyasato** [comment]
I am less inclined to commit our loading script into a public repo because it lists actual server names, usernames, email addresses, etc.  Data that really shouldn't be made available to the public.  If I had to choose between committing the loading script and the Makefile, I'd lean toward committing the Makefile (which really would probably be the same as the one in the distribution).

If we commit our Makefiles, and one of you changes any of them, I assume there will be some sort of notification mechanism in place to let us know that we need to pull down a modified copy?

I have removed the reactome file from the Makefile.  The daily load starts at 5:05 pm tonight so this particular issue should be resolved by about 9:30 tonight.

**Comment by kltm** [comment]
Fair enough.

The proposed notification system in this case would be tagging or assigning you onto an item in the tracker once the code has changed. Whether by structured file, a shared Makefile, or any other bit of text in the repo, it would be good to be able to communicate the intended load for production via the repo. What would work best for your setup here?

**Comment by kltm** [comment]
And thank you for the loader update!

**Comment by kltm** [comment]
@stuartmiyasato looking at the activity from uptimerobot, have the new payloads been put into production? (If so, this can be closed.)

**Comment by stuartmiyasato** [comment]
Yes, the loads finished last night.  A quick look at http://amigo.geneontology.org/amigo/load_details shows that the reactome file has been excluded.

Silly question:  how do you close an issue?  :)

**Comment by kltm** [comment]
With a code commit, you can do it like:
```
This was hard; fixes #123.
```
There are various key words you can use: https://help.github.com/articles/closing-issues-via-commit-messages/

From this page, there is the "Comment" button, and to its left, the "Close and comment" button.

**Comment by stuartmiyasato** [comment]
Wow, I'm completely blind.  :)  I think I got distracted by the big green "Commit" button and assumed the button next to it was 'cancel."  Doh!  :)  Okay, closing this issue!

**Comment by cmungall** [comment]
Looks like this was never done. See #211

**Comment by kltm** [comment]
I wonder if it could have been that the change was clobbered by a configuration copy during an update? That opposite seems to be the case for us: while we have all references to gene_association.reactome.gz removed from the repo, the old Makefile staggers on in the jenkins-slave (@cmungall will get that fixed for labs).

**Comment by cmungall** [comment]
Can you point to the production Makefile?

**Comment by stuartmiyasato** [comment]
I just checked on the GOlr loading machine and verified that reactome is NOT being loaded in production.

**Comment by cmungall** [comment]
Hmm, our primary hypothesis is that clobbering is happening, need to investigate where in the set of files this is happening. It sure *looks* like a reactome clobbering
