### ISSUE TITLE
Consistency in "annotations"/"associations" naming practices (term page)

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#217]
when you land on AmiGO with a term search (the way we link in)

This page, has links to i) gene products and ii) annotations (I use these links a lot)
http://amigo.geneontology.org/amigo/term/GO:0004674

However, the 'annotations link' is the same as the  first tab (called "Associations")

A Shouldn't these be consistently named? (Annotations?)

and

~~B  Shouldn't we have a corresponding tab for "gene products" (I actually find the gene 'products' link the really useful because it gives me the actual numbers. This would probably be the same for others if they knew, but its quite hidden)~~

**Comment by kltm** [comment]
There are some subtle differences in there.

The "annotations" link takes you to the Search interface, where you have more power than you do in the embedded interface on the term page. This was actually a requested feature.

For **A**, I'm happy to name things whatever people want, but somebody somewhere had a preference for "annotations", possible keeping "associations" around for historical reasons.

For **B**, maybe so, but we should open that as a separate issue as it is not related to naming. Questions to answer would be direct/indirect and what closure to use.

**Comment by kltm** [comment]
Actually, for **B**, maybe we could bring that up at the next meeting or something? In both cases, the information you want is a click away; maybe if the link out was more prominent? Early on, we had more sub-searches available, but in the end came down to one as they were considered confusing.

**Comment by cmungall** [comment]
**A** I have a personal pref for associations since outside the GOC world people understand different things by the term. But GOC preference would probably be for annotation, so in the interests of consistency we should go with that

**B** I don't know what to suggest. I like the power in the current interface but it's not really intuitive, and we are making the user conform to how we store the data in solr rather than making things easy for the user. in the interests of not getting caught in a cycle of switching the UI back and forth we should proceed carefully, document some usage scenarios that justify the way we do it.

I think the ideal scenario may be a single tab called 'Associations', as we have now, but with a way to switch back and forth as to whether we are showing one-line-per-annotation or one-line-per-gene. The "link to ..." button might better be reframed in terms of "build a query using this term..."

**Comment by kltm** [comment]
Either way, **B** should be split into a separate issue, for discussion if nothing else.

**Comment by selewis** [comment]
A. My preference is all for associations.

B. +1 for Chris's suggestion. Would like to see it in action before
offering a stronger opinion

On Thu, Jun 18, 2015 at 1:01 PM, kltm <notifications@github.com> wrote:

> Either way, *B* should be split into a separate issue, for discussion if
> nothing else.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geneontology/amigo/issues/217#issuecomment-113273831>.
>



-- 
In the long history of humankind (& animal-kind too) those who learned to
collaborate & improvise most effectively have prevailed - Charles Darwin

**Comment by ValWood** [comment]
I'll move B into a new ticket.
