### ISSUE TITLE
AmiGO labs URLs in models tab links to production, rather than labs

### ISSUE THREAD

**Issue by cmungall** [geneontology/amigo#236]

**Comment by kltm** [comment]
A little trouble parsing the title--links and examples are helpful.

**Comment by cmungall** [comment]
http://amigo2.berkeleybop.org/amigo/search/model_annotation

row 1 column 1, links to here
http://amigo.geneontology.org/amigo/term/GO:0098772

**Comment by kltm** [comment]
Ah. Well, actually, this is the expected behavior there as there are no manual overrides in the linker, meaning that there will fall back to db-xrefs.yaml (and the main site). Quick and dirty...and I wasn't thinking about that at the time--I conceptually am having a hard time thinking of this as a "real" AmiGO component. Easy enough to fix though.

**Comment by cmungall** [comment]
low priority, but once #237 is implemented on labs the behavior will become a bit annoying, since we'll be wanting to use the full power of amigo to interrogate models in labs, and won't want to keep getting kicked out
