### ISSUE TITLE
Search on MF "cyclin-dependent protein kinase activity" now retrieves "regulators"

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#267]
http://amigo2.berkeleybop.org/amigo/search/bioentity?q=*:*&fq=regulates_closure:%22GO:0004693%22&sfq=document_category:%22bioentity%22

retrieves protein kinases AND the cyclins (and other protein kinase regulators).

Previously  in GO, for MF, there was no annotation transitivity over regulates 9annotatiosn were only inherited over BP terms)

So for this term there are 25 annotations, when there should only be 4

**Comment by kltm** [comment]
Would like some commentary from @cmungall about this before proceeding.

**Comment by cmungall** [comment]
@ValWood is correct, the desired default behavior is not to propagate over regulates in MF

To simplify, let's start with the term page, which shows the list of associations inferred for a term (rather than Val's link, for the distinct bioentities)

http://amigo2.berkeleybop.org/amigo/term/GO:0004693

For an MF page the desired behavior is more or less to show the results of the isa-partof-closure, and for a BP page to show regulates-closure by default. If this sounds a little ad-hoc, it is, but #201 provides an elegant all encompassing solution that essentially delegates control of the behavior to the ontology group. This has other advantages to, pages should 'do the right thing', even if you end on a CHEBI, CL or UBERON term. It will also 'do the right' thing in terms of propagating down has_part within MF, required by @dosumis' refactor. The key is to stop thinking about ad-hoc propagation rules and think in terms of asserted and inferred relationships between genes and terms.

Anyway, in the context of the current amigo/golr architecture, understanding @ValWood's issue comes down to the fact the default closure (regulates) is a poor choice for MF, as it includes regulators of MFs, which the genes do not have involvement in.

Then when Val wants to see a gene-centric view of this GO term rather than an association view, she clicks on  [LINK to all genes and gene products annotated to cyclin-dependent protein serine/threonine kinase activity. ](http://amigo2.berkeleybop.org/amigo/search/bioentity?q=*:*&fq=regulates_closure:%22GO:0004693%22&sfq=document_category:%22bioentity%22)

(We already know this is a suboptimal way of showing distinct entities for a term, but it's what we have right now)

At this point the user has already "chosen" the regulates closure. This is why @kltm finds it curious that Val expects to see regulates excluded when she has already "chosen" the regulates closure.

But of course, the user doesn't really choose the closure, it's foisted on them by the previous page!

So here is a quick hack for Val.

If you end up on a page like 

http://amigo2.berkeleybop.org/amigo/search/bioentity?q=*:*&fq=regulates_closure:%22GO:0004693%22&sfq=document_category:%22bioentity%22

Just change the closure like this:

http://amigo2.berkeleybop.org/amigo/search/bioentity?q=*:*&fq=isa_partof_closure:%22GO:0004693%22&sfq=document_category:%22bioentity%22

ta-da! 4 PomBase genes.

Of course, I cringe as I provide this solution.

Hopefully that describes the problem. As to a proper solution, I suggest

 1. EITHER pushing ahead with #201 OR
 2. Quick fix: create a new ticket for context-sensitive closure selection (e.g default to regulates, on MF switch to I/P)

Additionally, I also recommend a new ticket dedicated to a better way of dealing with the user requirement of switching from listing distinct associations to distinct entities

**Comment by kltm** [comment]
Yes, my recollection was that the solution to this had been defined previously, and you found some in #201; but I think this is largely a dupe of #210, yes?
