### ISSUE TITLE
which site and  links current?/ linking in

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#268]
When I go to Amigo the link I usually use is
http://amigo.geneontology.org/amigo

This still says
AmiGO is temporarily experiencing an issue with the load and is failing back to this auxiliary site.
(is this still true?-  if so I don't really know what this means, should it be more explicit? I thought we were now back to normal)

All links in to AmiGO from PomBase are broken
http://amigo.geneontology.org/cgi-bin/amigo/term_details?term=GO:0031138
so if you do a redirect, maybe it needs to be implemented for all pages, not just the main page?

**Comment by ValWood** [comment]
This made me realize I can't test because I can only access the replacement AmiGO2?

Happy to test when I know which version is the fixed one, and how to get to it.

Val

**Comment by kltm** [comment]
The standard production AmiGO out of Stanford has had a series of Unfortunate Events, and is now passing control back to what is usually a testing instance at Berkeley. This is referenced in the warning message link for "issue", which links to #262.

As part of this exceptional process, the large number of forwards supported by Stanford to deal with legacy systems has not been implemented. If we cannot get the production systems ticking over soon, we'll look to implement them on this backup system. It would be worth considering no longer using the legacy links in PomBase, e.g.:

 http://amigo.geneontology.org/cgi-bin/amigo/term_details?term=GO:0031138

and switching over to the modern ones:

 http://amigo.geneontology.org/amigo/term/GO:0031138

Linking information is documented here:

 http://wiki.geneontology.org/index.php/AmiGO_2_Manual:_Linking_To_AmiGO_2

**Comment by ValWood** [comment]
ok will do

How can I the updates- Which URL would I use for this?
@cmungall asked that I look

**Comment by kltm** [comment]
@ValWood, I'm not quite following: which URL should you use for what?

**Comment by ValWood** [comment]
(The bugs I submitted were using the current live implementation, not the 'fixed' version)

**Comment by kltm** [comment]
The incoming URLs will be the same either way.

**Comment by ValWood** [comment]
Chris asked me to test if everything looked OK, but AFAIK  (based on the message), we are currently using the 'auxillary site' which you switched to  when the problem occurred (i.e which predated the reported issue).

Maybe I have misunderstood what the message means?

**Comment by kltm** [comment]
I think I'm only getting half of the conversation here--I'm not sure about the message from @cmungall, but I think the target is the links in PomBase failing to resolve? This is because the "backup" system does not currently resolve any legacy URLs. However, the backup system is perfectly fine with the "modern" URLs defined above.

**Comment by ValWood** [comment]
Chris mentioned taking a look to see if the issues were resolved int he helpdesk ticket (I think).

I tried, but I am not sure what I am looking at. The current live version (according to the message) is the fallback site? That went up before the fix, so I am presuming this is not what I should be testing?
I think I probably don't understand what the different sites are.

The PomBase link thing is clearly incidental, ignore this.

Where should I go to test the numbers  look OK in the  version of Amigo that was fixed as a result of the issues identified in the original helpdesk ticket?

**Comment by kltm** [comment]
Okay, now I'm confused. You might want to fold some of this back into the ticket you're referencing--this thread is specifically about the links in PomBase. It's possible this in in reference to the bad load, which would be ticket #262. The current load that you see (if you go to amigo.geneontology.org) should be "fixed".

**Comment by cmungall** [comment]
Here's the sequence of events

 1. We notice the production load is broken in http://jira.geneontology.org/browse/GO-1011
 2. Because Stuart is away, we decide to use an instance in berkeley as the backing for production
 3. I announce the major problem is resolved

However, it turns out (2) has some quirks, and is not a true mirror of what we aim to have working on production. Not all URLs work the same way it seems (assume because redirects are a separate layer handled directly at production). The message shown in amigo is potentially a bit confusing: what should a user understand by 'falling back to auxiliary site'? Is the data the same? (yes, it should be; the egregious load issue is fixed). Is the behavior the same? (no, there are minor differences, such as with the legacy URLs, medial search has some spoilers about potential lego model search, but none of this is related to the data load, which should be flawless).

On reflection I should have better clarified about the situation being resolved, and the banner message in amigo2 labs should link to a news article describing the situation more clearly. Anyway, hope that clarifies. Val, let us known if there are any other issues you spot.

**Comment by ValWood** [comment]
Got it. Will do a little testing and report any issues I spot.

**Comment by kltm** [comment]
@cmungall, we can change the message and somewhat "production-ify" our backup (e.g. replace message with one about legacy links temporarily down, make internal linking consistent, remove hidden search aspects, etc.) if that would clarify things. The current setup was, to some extent, to make users a little jumpy and realize that things were in a poor state. We can talk about this off the tracker if there is time.
