### ISSUE TITLE
AmiGO filtering

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#299]
I was going to open a helpdesk ticket for this but jira appears to be down. I don't know if this is due to general problems at stanford as I had problems accessing AmiGO for the past hour two.

I am trying  to get some numbers form either QuickGO  or AmiGO for a paper.

First off, its really hard to get to top level of AmiGO if you just wanted to filter all annotations on specific taxon  (fungi) and experimental  evidence.

To do this I ended up typing a random search, accessing the “annotation” link and then deleting the remaining free text filter. I could not find any other way  to access at this point from the top level pages?

I then wanted to apply filters to see how many manual annotations  there were to which fungal species.
I thought I would filter on taxon “fungi’ and “experimental evidence codes.
I forgot that I could not filter on  taxon groupings. Instead I filtered only on evidence, thinking that I could then remove the species I was not interested in, which would be tedious but should be possible.
Here I got stuck because after I removed human and mouse AmiGO would not let me apply any more filters?

I have a similar problem with QuickGO. With QuickGO I would be able to apply the appropriate filter because you can supply any grouping ID. However  again, I don’t know of a way to see all annotations (I think you would need to do each ontology root node independently). Perhaps you can do this in the new QuickGO?

If anyone has any ideas I’d be really grateful….

I can't access Goose right now either, but I always have trouble getting large queries to complete...

I can migrate this to another more appropirate tracker on Monday if desired.

**Comment by kltm** [comment]
Stanford has been fighting a crawler for the past week or so; there have been some outages associated with it.

We don't have anything quite like you describe, but if it is a common use case, we could add something like that to Grebe (http://amigo.geneontology.org/grebe) very easily. Due to attempting to fix what some users saw as too many species in the taxon filter, a series of changes around #209 occurred, eliminating easy selection.

GOOSE should be available now.

If I were to try and get what you wanted out of the current AmiGO interface, it would look like:

- go to Grebe] > [Annotations] http://amigo.geneontology.org/grebe
- under "Term annotations", use the second box to input and select "fungi" (NCBITaxon:4751) and "biological_process" (GO:0008150); click "Go>"
- on the annotation search page that opened up, remove the "isa_partof_closure: GO:0008150" filter
- select "experimental evidence" from the "Evidence type" filter

**Comment by cmungall** [comment]
Yes, this should be much simpler when #/247 is done

For now, your protocol seems to work perfectly for this Seth (could we make the term field optional, to avoid the remove filter step? Getting an overview of everything for a given taxon is not an uncommon scenario. We need videos and tutorials showing how to do all this!

**Comment by kltm** [comment]
Easy enough. For the interim, have added #302.

**Comment by ValWood** [comment]
I was trying to follow the above. I'm confused at step 1.

The results look like this:
![stuck](https://cloud.githubusercontent.com/assets/7359272/13176767/6e1ff28c-d70c-11e5-8a2d-8360dbf595d8.jpg)

**Comment by kltm** [comment]
@ValWood Your last comment seems to have not shown up here. Could you try again?

**Comment by ValWood** [comment]
I can't remember what it was? There was a comment yesterday that I posted and immediately deleted. It was a non issue(although I didn't think it was on this ticket?).
