### ISSUE TITLE
Add grebe template for common counts

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#302]
We would like a grebe template for the following page/steps:

- go to [Grebe] > [Annotations] http://amigo.geneontology.org/grebe
- under "Term annotations", use the second box to input and select "fungi" (NCBITaxon:4751) and "biological_process" (GO:0008150); click "Go>"
- on the annotation search page that opened up, remove the "isa_partof_closure: GO:0008150" filter
- select "experimental evidence" from the "Evidence type" filter

As this is only a change to a configuration file, we should be able to get this into product before the next release.

From @ValWood and #299, with @cmungall .

**Comment by ValWood** [comment]
I *never* use grebe. Mainly because I forgot about it.

Yet I come to this page every week....
http://amigo.geneontology.org/amigo
I see it, but I ignore it because it isn't really clear what it does.

Calling it "Grebe" makes it sound like it's something outside of AMiGO, how about labelling it AmiGO search templates"?

**Comment by kltm** [comment]
Yes, that's probably a good idea.

**Comment by kltm** [comment]
Now have #303.

**Comment by kltm** [comment]
A lot more runaround than intended, but the fixes and new template should be in. Future templates will be that much easier.
