### ISSUE TITLE
Confirmation of numbers and potential weirdness

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#304]
Chris provides this, and I think these sources /numbers are correct for PomBase and SGD

![screen shot 2016-02-18 at 1 35 51 pm](https://cloud.githubusercontent.com/assets/7359272/13176218/43d59e5e-d708-11e5-8847-53e24f40d8df.jpg)

**Comment by ValWood** [comment]
There is something slightly weird and I can't work out what it is.

The AspGD annotations have source AspGD (here), but I think they also have source uniprot (at least when I filter on Uniprot source, I still see the AspGD attributed annotations)

I think we would be better for these purposes to use "assigned by". This reflects the original source of the annotation ( AspGD) even though it no longer exists

**Comment by ValWood** [comment]
Okay got it

I will use attribution instead

![got it](https://cloud.githubusercontent.com/assets/7359272/13176840/f74cec54-d70c-11e5-8044-ae20fb6b4a72.jpg)

There are 2 sets of AspDB annotations. One set gets attributed to AspDB and one set to UniProt

**Comment by ValWood** [comment]
Other than that  the AspDB confusion above I think the numbers are OK. Its confusing because Uniprot is now the source of the CGD and some of the AspDB annotations. Uniprot assigned by is 1087.

We will use assigned by and these numbers

**Comment by ValWood** [comment]
Would be good to know if this AspDB data is really 2 independent datasets of if it is partly redundant.

**Comment by ValWood** [comment]
Yeah there is a wild difference here between the Intact annotation in GOA and those in Amigo (for SGD GOA have  11796 (assigned by intact)

**Comment by kltm** [comment]
Tagging @cmungall

**Comment by kltm** [comment]
Coming up on half a year here; comment or close from @cmungall ?

**Comment by cmungall** [comment]
Yes, still an issue, we have duplicate annotations from aspgd, those coming first hand from the aspgd gaf and those coming from EBI-GOA. (A secondary issue is that GOA capitalizes the name rather than using the xrefs.yaml entry).

OK, so Mike's script assumes the following two taxa are owned by aspgd:

```
    'taxon:162425' => 'aspgd',
    'taxon:5085' => 'aspgd',
```

That's fumigatus and nidulans respectively

[[[OK, a sidebar with something I'm finding v confusing - there appear to be 2 IDs for fumigatus in NCBI taxonomy:

http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=5085
http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=746128

both are identical, no indication if one is retired. But in the very latest download of taxonomy.dat from the NCBI ftp site, 5085 is gone without a trace, arghhh

]]]

Anyway, the actual list of taxa in the aspgd gaf are:

 * NCBITaxon:746128 _Aspergillus fumigatus_
 * NCBITaxon:162425 _Aspergillus nidulans_
 * NCBITaxon:5061 _Aspergillus niger_
 * NCBITaxon:5062 _Aspergillus oryzae_
 * NCBITaxon:41063 _Aspergillus zonatus_
 * NCBITaxon:46472 _Aspergillus versicolor_
 * NCBITaxon:75750 _Aspergillus sydowii_
 * NCBITaxon:1033177 _Aspergillus kawachii IFO 4308_
 * NCBITaxon:1073089 _Aspergillus wentii DTO 134E9_
 * NCBITaxon:1137211 _Aspergillus foetidus CBS 106.47_
 * NCBITaxon:1160497 _Aspergillus glaucus CBS 516.65_
 * NCBITaxon:331117 _Neosartorya fischeri NRRL 181_
 * NCBITaxon:332952 _Aspergillus flavus NRRL3357_
 * NCBITaxon:341663 _Aspergillus terreus NIH2624_
 * NCBITaxon:344612 _Aspergillus clavatus NRRL 1_
 * NCBITaxon:451804 _Aspergillus fumigatus A1163_
 * NCBITaxon:602072 _Aspergillus carbonarius ITEM 5010_
 * NCBITaxon:690307 _Aspergillus aculeatus ATCC 16872_
 * NCBITaxon:767769 _Aspergillus brasiliensis CBS 101740_
 * NCBITaxon:767770 _Aspergillus tubingensis CBS 134.48_

The solution is to go through and add each of these individually to the dictionary in the script (assuming aspgd is considered authoritative for each of these taxa)

We will be transitioning from the script to having a metadata file for each contributing database. For a preview:

https://github.com/geneontology/go-site/blob/master/metadata/datasets/aspgd.yaml

**Comment by cmungall** [comment]
Fix here: http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/software/utilities/filter-gene-association.pl?r1=33947&r2=34909

should take about 1wk to percolate
