### ISSUE TITLE
Download of 10k genes failing on production

### ISSUE THREAD

**Issue by cmungall** [geneontology/amigo#391]
metabolic genes in homo sapiens

http://amigo.geneontology.org/amigo/search/bioentity?q=*:*&fq=regulates_closure:%22GO:0008152%22&fq=taxon_subset_closure_label:%22Homo%20sapiens%22&sfq=document_category:%22bioentity%22

only 10k. Custom DL, default 2 fields times out. Runs in milliseconds on tomodachi

reboot required?

cc @kltm

**Comment by kltm** [comment]
@stuartmiyasato before rebooting (if that is indeed that correct course of action here), would it be possible to know what the usage on the machine is? I'm wondering if this is a bot or a killer query.
As @cmungall said, these queries go quite fast on our local machines, so I'm a little worried.
It's a bit strange that the Solr index seems to be otherwise responsive.

**Comment by kltm** [comment]
It seems like this is connected to a GO Helpdesk query: http://jira.geneontology.org/browse/GO-1355
```
'm using the search function to download the names of approximately 60K Homo
sapiens genes related to the search term "metabolic". The interface says that
downloads are possible for lists under 100k, but I'm getting a "504 Gateway
Time-out" error. Is there any way around this?
```
The 100k should be fine for us in most cases from the benchmarking we did.

**Comment by cmungall** [comment]
Yes, this is the response I started writing:

```
Hi,

First I would caution you against using string based searches like "metabolic". One of the points of the gene ontology is that it can return all genes associated with a concept regardless of whether a the string is in the name of the annotation.

For example, in AmiGO you can search for 'metabolic process' http://amigo.geneontology.org/amigo/term/GO:0008152

Click ' Link to all genes and gene products annotated to metabolic process. '

Then select 'Homo sapiens'

You can then download the 10k genes annotated to 'metabolic process'

UH OH
```

**Comment by stuartmiyasato** [comment]
The issue appears to have been an nginx (non-)configuration.  I increased the proxy timeout configuration and it seems to have fixed the problem.  @cmungall can you check to make sure it works properly for you?

For the record, I added the following configuration directives in our nginx.conf file:

> 
proxy_connect_timeout 600;
proxy_send_timeout 600;
proxy_read_timeout 600;
send_timeout 600;

**Comment by kltm** [comment]
@stuartmiyasato It certainly seems to be working better now, with results returning almost immediately.
Unfortunately, this was not the behavior yesterday, where it would spin until timing out--it seemed like something on the server was struggling.
Oh well, it looks to be cleared now :)

**Comment by kltm** [comment]
@stuartmiyasato The uptimerobot really only does pingable, not system stress, etc.
IIRC, you have nagios on the solr servers? Besides up/down, do you keep time series for CPU/RAM?

**Comment by stuartmiyasato** [comment]
@kltm We do keep those stats, but it's not completely representative because the GOlr services are bundled on the same VM as AmiGO so it's not easy to separate which service is using what resources  at any given moment.  It will be easier to do so once the services are decoupled, probably once they are deployed into AWS.  Having multiple servers behind a load balancer doesn't make it any easier to monitor either...

That said, with reference to http://jira.geneontology.org/browse/GO-1364, I would be surprised if it's a resource limitation.  Without having looked at the problem at all, my gut feeling is that there's a bad service configuration in there somewhere -- probably the nginx config for GOlr.  Will have to investigate further.

**Comment by kltm** [comment]
@stuartmiyasato Thank you for looking into this more.

I that, pretty much besides the visualize stuff, which is pretty out of the way, most things in AmiGO are passed through to the Solr backend. I'd wager that unless the visualize is more used than I think, load should pretty much be on the Solr server.

I was guessing at resource limitation given that there seems to have been a "spike" (well, two) in people having issues with the disk-centric download operations.
Given our testing for seeing what would happen at 100k, I'd think that even a large volume of small requests would not sweat the system.

Ah well, if anything comes up, let me know. Hopefully, if it comes up again, we can catch it in the act.

**Comment by kltm** [comment]
This seems to be coming up again with http://jira.geneontology.org/browse/GO-1369 .

**Comment by kltm** [comment]
No current complaint, I believe. Will close for now.
