### ISSUE TITLE
"Data health" link needs to be replaced or removed

### ISSUE THREAD

**Issue by pgaudet** [geneontology/amigo#565]
Hello,

The 'datahealth' icon on the AmiGO annotation pages goes to a 404 page on the website: 

<img width="1320" alt="image" src="https://user-images.githubusercontent.com/4782928/56743208-751ac000-6776-11e9-90ce-a3d807c16ac2.png">

- Can the link go to the help email ? 
- And can the label be changed to 'Send Feedback'? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Can you please assign someone to this ?

**Comment by kltm** [comment]
@ukemi 
Okay, looking at this, it is a link to the old "form". Currently, we no long have a form (long-form anonymous text input in the browser). The immediate options are:

1) Remove data health tags; as far as I know these links have never been used anyways, so little loss
2) Turn it into a preloaded `help` *at* `geneontology.org` "mailto" link; easy, but may be a spam magnet
3) Turn it into a link to a GH data form, like https://github.com/geneontology/helpdesk/issues/new?assignees=&labels=&template=issue-report.md&title=Data+Narfed ; easy, but requires GH account.

I would suggest 3, then 1. 2 I believe will cause more churn than help.

This can be revisited once we get whatever comes next for the helpdesk setup.

**Comment by pgaudet** [comment]
We need to provide an easy way for users to contact the consortium from AmiGO. If this is not it, where would we put that link ? 

Thanks, Pascale

**Comment by ValWood** [comment]
I agree, there should be a "contact" link on every consortium/amigo page.  And it shouldn't say "data health"

**Comment by ukemi** [comment]
I agree. Doesn't it make most sense to just put the 'contact us' link on the pages similar to the way it is on the home page?

**Comment by ukemi** [comment]
For consistency, shouldn't the same footer go on all GOC pages?

**Comment by kltm** [comment]
Okay, some history for this is here: https://github.com/geneontology/amigo/issues/365 . TL;DR: This was not meant to be a "contact us" thing from the beginning. There was some more off-tracker discussion on this, but it's not at hand.

I'm more than happy to get rid of it in favor of a more homepage-like footer. (The literal footer cannot be reused, but we can get something with similar information.)

@ukemi Ideally, there is not a lot of iteration on this. With #566 we'll already be kicking to something "functional". I would propose then:

* Remove "data health"--its time has apparently passed
* Add additional information to left side of AmiGO footer (as right is already version info)
  * (Ignoring "Feedback" in the upper menu) Change left footer's third item to "Contact us (Helpdesk)"

Otherwise, if the changes cannot be explained in simple text here, could somebody put together a mock-up of what they want it to look like, including the additional versioning information.

**Comment by pgaudet** [comment]
Can this close?

**Comment by kltm** [comment]
Seems to work, no longer 404.
