### ISSUE TITLE
Filter for UCL as source

### ISSUE THREAD

**Issue by RLovering** [geneontology/amigo#571]
Hi
I would like to be able to find UCL annotations in AmiGO by using the Source filter. However this is not possible as the source of all UCL annotations is listed as UniProt. Would it be possible to have the 'assigned by' information available as a filter?

Thanks

Ruth
@ValWood @BarbaraCzub

**Comment by kltm** [comment]
@RLovering I may be misunderstanding what is being asked here. For the loaded data, `assigned_by` is accessed by the "Contributor" filter. For example:

http://amigo.geneontology.org/amigo/search/annotation?q=*:*&fq=assigned_by:%22BHF-UCL%22&sfq=document_category:%22annotation%22

```
BHF-UCL | (42619)
ParkinsonsUK-UCL | (6912)
ARUK-UCL | (6893)
SynGO-UCL  | (140)
```

**Comment by RLovering** [comment]
that is wonderful, sorry I missed that before. There seems to be some inconsistencies, perhaps it is my browser, your link worked great but this one from Val: http://amigo.geneontology.org/amigo/search/bioentity?q=*:*&fq=isa_partof_closure:%22GO:0006520%22&fq=isa_partof_closure:%22GO:0051186%22&fq=-isa_partof_closure:%22GO:0034628%22&fq=-isa_partof_closure:%22GO:0034354%22&fq=-isa_partof_closure:%22GO:0019442%22&fq=-isa_partof_closure:%22GO:0008705%22&sfq=document_category:%22bioentity%22 has no contributor option.

any thoughts?

Thanks for getting back to me so quickly

Ruth

**Comment by kltm** [comment]
@RLovering No problem

The issue here is that my bookmark/location is for the `annotation` search, while Val's is for `bioentity` search. As it stands now, as the cross-cut combinatorics of doing these facets for bioentities was too high (i.e. bioentity is already a grouping category for a lot of these properties, so `assigned_by` could be many and in that case what does one do with evidence), we only maintained them for annotations. The closest to what Val has there would be:

http://amigo.geneontology.org/amigo/search/annotation?q=*:*&fq=isa_partof_closure:%22GO:0006520%22&fq=isa_partof_closure:%22GO:0051186%22&fq=-isa_partof_closure:%22GO:0034628%22&fq=-isa_partof_closure:%22GO:0034354%22&fq=-isa_partof_closure:%22GO:0019442%22&fq=-isa_partof_closure:%22GO:0008705%22&sfq=document_category:%22annotation%22

Still nothing for UCL, but is you remove the `isa_partof_closure: GO:0006520` filter, you can see yourselves down there in the "Contributor" facet.

**Comment by ValWood** [comment]
The Matrix output is necessarily "gene product" rather than annotation (thats what the Matirc outputs).

I guess when the MAtrix rules are merged into the individual group reports this will need to be dealt with.

In the meantime, Ruth don't worry  I will raise tickets for any outstanding questions in the intersection annotations. I have probably done about 50%  of the term intersections  I plan to check so there shoud not be so many  more for you....
