### ISSUE TITLE
Replace software page with link to GO Tools page

### ISSUE THREAD

**Issue by pgaudet** [geneontology/amigo#579]
Can the AmiGO link to 'Tools' link to http://geneontology.org/docs/tools-overview/
so it's the same as on the geneontology.org website ?

**Comment by kltm** [comment]
@pgaudet To clarify, are you asking that the "Tools & Resources" top menu item on all AmiGO pages points to the general GO page (http://geneontology.org/docs/tools-overview/), correct?

Easily done (although I'll leave hooks in there so another AmiGO sites can maintain this page as it is quite useful and the only way to get to some AmiGO functionality).

Looking at it, I'm a little worried about partially pulling the AmiGO-specific detailed tools information as some functionality may be lost; if it is all ported over, I'm not sure what the additional utility is.

**Comment by pgaudet** [comment]
Yes, this is what I was suggesting. Thanks for pointing out the differences. I think both these pages should have the same content. Should we extend the http://geneontology.org/docs/tools-overview/ ? 

@suzialeksander 
@ukemi 
@lpalbou

**Comment by suzialeksander** [comment]
I don’t think we should include, say, GOOSE on the main site, but I see we don’t have a link to Panther EA so adding general links like that would be great. We could incorporate some of the other links be rephrasing the description of AmiGO?

**Comment by ukemi** [comment]
I believe that GOOSE is cooked and at some point will be replaced with a SPARQL tool. So we should not include that. In my opinion, we should not port over tools that will be problematic.

**Comment by lpalbou** [comment]
Good idea to have a single tools page. I favor the main site rather than amigo for its simple and quick updates.

I agree with Suzi for adding Panther EA on the main site tool page.

I don't think GOOSE is useful anymore. We can add [rdf.geneontology.org](rdf.geneontology.org) for SPARQL. It mostly contains GO-terms and GO-CAMs but should soon include go annotations with dustin imports. 

If there is a use case for [searching a specific PMID](http://amigo.geneontology.org/amigo/software_list#reference-query-form), I would add a radio button below the search bar on the main site, rather than listing it in tools.

The amigo page [schema_details](http://amigo.geneontology.org/amigo/schema_details) would gain to be linked from [http://geneontology.org/docs/tools-guide/](http://geneontology.org/docs/tools-guide/#query-go-ontology-and-annotations-with-golr). If not generated automatically (@kltm ?), I would slowly move those documentations to the main site.

**Comment by kltm** [comment]
@lpalbou It is generated automatically.

Any additional items should be separate tickets.

**Comment by kltm** [comment]
GOOSE over here: https://github.com/geneontology/amigo/issues/574

**Comment by lpalbou** [comment]
Proposed action items from above comments:
- [ ] 1 - "Tools & Resources" amigo menu pointing to http://geneontology.org/docs/tools-overview/
- [ ] 2 - "Tools & Resources" page: kept for amigo functionalities but with different access
- [ ] 3 - include Panther EA tool description and link in http://geneontology.org/docs/tools-overview/ 
- [ ] 4 - include RDF/SPARQL endpoint rdf.geneontology.org in http://geneontology.org/docs/tools-overview/  (to be later revised with @cmungall, @dougli1sqrd and myself for a better query explorer and examples with sparqlr)
- [ ] 5 - link [amigo schema detail](http://amigo.geneontology.org/amigo/schema_details) from  http://geneontology.org/docs/tools-guide/#query-go-ontology-and-annotations-with-golr 
- [ ] 6 - add a search by PMID radio button option below the search bar of the main go site

With the publication of the GO-CAM article and recent Paul email:
- [ ] 7 - add a search GO-CAM option below the search bar of the main go site

@pgaudet can you confirm / adjust ?

Also linked to [ribbon doc](https://github.com/geneontology/geneontology.github.io/issues/21) and [ribbon sandbox](https://github.com/geneontology/geneontology.github.io/issues/179)

**Comment by suzialeksander** [comment]
@pgaudet is this still an active ticket?

**Comment by suzialeksander** [comment]
@pgaudet should I close this?

**Comment by kltm** [comment]
@suzialeksander @pgaudet I'd note that it could be closed on "not going to do it" grounds, but the (various) changes outlined above have not been acted on, so the original issue stands.

**Comment by pgaudet** [comment]
OK sure
