### ISSUE TITLE
Can we reroute MGI:XXX to MGI:MGI:XXX

### ISSUE THREAD

**Issue by lpalbou** [geneontology/amigo#601]
Old issue but it would be practical for other resources (like ribbon) referencing MGI ids on amigo to be able to use directly MGI:XXX (eg http://amigo.geneontology.org/amigo/gene_product/MGI:98941) instead of having to check for MGI IDs and duplicate on the fly to MGI:MGI:XXX (eg http://amigo.geneontology.org/amigo/gene_product/MGI:MGI:98941).

I am guessing this could be an issue also for other external resources.

**Comment by kltm** [comment]
Yes, MGI:MGI has been a sticking point for a while and has a bit of history. I think that we likely want to deal with this more globally as data, rather than goosing just AmiGO. Even if just AmiGO, I it would take a bit of fiddling to make it work out right.

https://github.com/geneontology/go-site/issues/346
https://github.com/geneontology/go-site/issues/91

Tagging @cmungall 

If there is a desire to deal with this now, my preference would be to close this out and coordinate from the go-site ones (upstream data and metadata issue).

**Comment by pgaudet** [comment]
Out of date.
