### ISSUE TITLE
PMID eutilities has changed their API breaking AmiGO pub pages

### ISSUE THREAD

**Issue by cmungall** [geneontology/amigo#657]
https://twitter.com/NCBI/status/1595145616161505281

http://amigo.geneontology.org/amigo/reference/PMID:15626502

<img width="770" alt="image" src="https://user-images.githubusercontent.com/50745/203597735-139ef615-ca3c-457b-b140-9604ae9ff81e.png">

**Comment by kltm** [comment]
Specifically: 
https://ncbiinsights.ncbi.nlm.nih.gov/2021/10/05/updated-pubmed-api/

We're using:
`https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?tool=XYZ&email=sABC&retmode=XML&db=pubmed&id=15626502`

According to their description of changes, there is no required change at our end. If there was an issue, it might have been related to the switchover or a hiccup, rather than an API change that's breaking for us.

**Comment by ValWood** [comment]
@kimrutherford
